ALTER TABLE t_p84704826_gamified_habit_app.tasks
  ADD COLUMN IF NOT EXISTS extension_requested BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS extension_granted BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS extension_hours INTEGER DEFAULT NULL;
