ALTER TABLE t_p84704826_gamified_habit_app.parents
    ADD COLUMN IF NOT EXISTS is_premium_paid BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS premium_until TIMESTAMP WITH TIME ZONE NULL;